apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unipark-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: unipark.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unipark-service
                port:
                  number: 8000
